services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: muchtodo-api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    ports:
      - "8080:8080"

volumes:
  mongo_data:
